version: '3.1'
services:
  db:
    #image: thedifferent/mariadb
    build: mariadb
    environment:
      - "MYSQL_ROOT_PASSWORD=secretsecret"
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wp"
      - "MYSQL_PASSWORD=secret"

  wordpress:
    #image: thedifferent/wordpress
    build: wordpress
    depends_on:
      - "db"
    ports:
      - "80:80"
    environment:
      - "DB_HOST=db"
      - "DB_NAME=wp"
      - "DB_USER=wordpress"
      - "DB_PASSWORD=secret"
      - "WORDPRESS_SITE_URL=https://thedifferent.at"
