version: '3.1'

services:
  db:
    image: thedifferent/mariadb:gina
    #build: mariadb
    networks:
      - "local"
      - "dbgui"
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD_LOCAL=true"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=wp"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "WP_GINA_GIT_REPO=${GINA_GIT_REPO}"
      - "DB_GINA_GIT_USER=${GINA_GIT_USER}"
      - "DB_GINA_GIT_PASSWD=${GINA_GIT_PASSWD}"
      - "DB_GINA_INTERVAL=${GINA_INTERVAL}"
    resources:
      limits:
        cpus: '0.30'
        memory: 512M
      reservations:
        cpus: '0.15'
        memory: 256M

  wordpress:
    image: thedifferent/wordpress-alpine:gina
    #build: wordpress
    depends_on:
      - "db"
    networks:
      - "local"
      - "rvproxy"
    ports:
      - "${WP_PORT}:80"
    environment:
      - "DB_HOST=db"
      - "DB_NAME=wp"
      - "DB_USER=wordpress"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "WORDPRESS_SITE_URL=${WP_SITE_URL}"
      - "WP_BACKUP_URL=${WP_BACKUP_URL}"
      - "WP_GINA_GIT_REPO=${GINA_GIT_REPO}"
      - "WP_GINA_GIT_USER=${GINA_GIT_USER}"
      - "WP_GINA_GIT_PASSWD=${GINA_GIT_PASSWD}"
      - "WP_GINA_INTERVAL=${GINA_INTERVAL}"
    resources:
      limits:
        cpus: '0.50'
        memory: 2048M
      reservations:
        cpus: '0.30'
        memory: 768M

networks:
  local:
    driver: overlay
  dbgui:
    external:
      name: adminer-net
  rvproxy:
    external:
      name: traefik-net

volumes:
  db-data:
    driver: local
