version: '3.1'

services:
  db:
    image: thedifferent/mariadb
    #build: mariadb
    networks:
      - "wp-net"
    environment:
      - "MYSQL_ROOT_HOST=localhost"
      - "MYSQL_ROOT_PASSWORD_LOCAL=true"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=wp"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    #resources:
    #  limits:
    #    cpus: '0.3'
    #    memory: 512M
    #  reservations:
    #    cpus: '0.15'
    #    memory: 256M

  wordpress:
    image: thedifferent/wordpress-alpine
    #build: wordpress
    depends_on:
      - "db"
    networks:
      - "wp-net"
    ports:
      - "${WP_PORT}:80"
    environment:
      - "DB_HOST=db"
      - "DB_NAME=wp"
      - "DB_USER=wordpress"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "WORDPRESS_SITE_URL=${WP_SITE_URL}"
    #resources:
    #  limits:
    #    cpus: '0.50'
    #    memory: 1024M
    #  reservations:
    #    cpus: '0.25'
    #    memory: 512M

networks:
  wp-net:
    driver: overlay
