version: '3'
services:
  db:
    build: .
    environment:
      - "MYSQL_ROOT_PASSWORD=secretsecret"
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wp"
      - "MYSQL_PASSWORD=secret"

  wordpress:
    image: thedifferent/wordpress
    depends_on:
      - "db"
    ports:
      - "80:80"
    environment:
      - "DB_HOST=db"
      - "DB_NAME=wordpress"
      - "DB_USER=wp"
      - "DB_PASSWORD=secret"
      - "WORDPRESS_SITE_URL=https://localhost"
    restart: always
